#!/bin/bash
TYPE="stat"

SITE_ROOT=$(realpath $(dirname $(realpath $0))/..)
SITE_ROOT1=$(echo $SITE_ROOT | sed 's/\//\\\//g')
export HOME=$SITE_ROOT
ROOT_DIR=$SITE_ROOT

source $SITE_ROOT/scripts/base.sh

cd $SITE_ROOT

mbr_root=/massbit/massbitroute/app
service_dir=$mbr_root/src/sites/services
chmod +x $SITE_ROOT/scripts/run

ASDF=$SITE_ROOT/bin/.asdf/installs
LOKI=$ASDF/loki/v2.6.1/bin/loki
GRAFANA_DIR=$ASDF/grafana/v8.2.1
GRAFANA=$GRAFANA_DIR/bin/grafana-server
_repo() {
	if [ -z "$MBR_ENV" ]; then
		echo "MBR_ENV missing"
		exit 1
	fi
	if [ -z "$GIT_PUBLIC_URL" ]; then
		echo "GIT_PUBLIC_URL missing"
		exit 1
	fi
	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
	export ASDF_BRANCH=latest
	export GBC_BRANCH=latest
	export MKAGENT_BRANCH=latest

	REPOS="\
	   $service_dir/mkagent|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_mkagent.git|$MKAGENT_BRANCH \
	 $mbr_root/gbc|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_gbc|$GBC_BRANCH \
	 $mbr_root/gbc/bin/.asdf|$GIT_PUBLIC_URL/massbitprotocol/massbitroute_asdf|$ASDF_BRANCH \
"

}


_run_test() {
	cd $SITE_ROOT
	export PATH=$PATH:$SITE_ROOT/bin/openresty/nginx/sbin

	supervisorctl stop mbr_${TYPE}_monitor

	if [ ! -f "$SITE_ROOT/src/env.lua" ];then
	   touch $SITE_ROOT/src/env.lua
	   else
	       > $SITE_ROOT/src/env.lua
	fi
	   
       

	env_src=$SITE_ROOT/env/env.lua
	if [ -f "$env_src" ]; then
		sed /PARTNER_ID/d -i $env_src
		sed /SID/d -i $env_src
		sed '/}/i ["PARTNER_ID"]="fc78b64c5c33f3f270700b0c4d3e7998188035ab",' -i $env_src
		sed '/}/i ["SID"]="403716b0f58a7d6ddec769f8ca6008f2c1c0cea6"' -i $env_src

		cp $env_src $SITE_ROOT/src/env.lua
		_reload
	fi

	if [ $# -ne 0 ]; then
		prove -r $@
	else
		prove -r t
	fi

}

_install_test() {
	apt update
	apt install -y make
	export PERL_MM_USE_DEFAULT=1
	yes | cpan -i Test::Nginx
	cd $SITE_ROOT
	ls -d $SITE_ROOT/.cpan/build/* /root/.cpan/build/* | while read d; do
		cd $d
		make install
		cd -
	done
}

_repo_private() {
	if [ -z "$MBR_ENV" ]; then
		echo "MBR_ENV missing"
		exit 1
	fi
	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
		echo "GIT_PRIVATE_READ_URL missing"
		exit 1
	fi
	if [ -z "$GIT_PRIVATE_BRANCH" ]; then
		echo "GIT_PRIVATE_BRANCH missing"
		exit 1
	fi

	export ENV_BRANCH=${ENV_BRANCH:-$GIT_PRIVATE_BRANCH}
	export SSL_BRANCH=${SSL_BRANCH:-$GIT_PRIVATE_BRANCH}

	_env
	REPOS_PRIVATE="\
$SITE_ROOT/env|$GIT_PRIVATE_READ_URL/massbitroute/env.git|$ENV_BRANCH \
/etc/letsencrypt|$GIT_PRIVATE_READ_URL/massbitroute/ssl.git|$SSL_BRANCH \
"
	REPOS_RUNTIME="\ 

"
}

_prepare() {
	echo "Prepare"
	mkdir -p \
		$SITE_ROOT/logs/nginx \
		$SITE_ROOT/db \
		$SITE_ROOT/tmp \
		$SITE_ROOT/db

}
_install_repos() {
	if [ -z "$MBR_ENV" ]; then
		echo "MBR_ENV missing"
		exit 1
	fi
	_repo
	_install_sources $REPOS
	_install_status=$?
	return $_install_status
}

_update_repos() {
	if [ -z "$MBR_ENV" ]; then
		echo "MBR_ENV missing"
		exit 1
	fi
	if [ -z "$GIT_PRIVATE_READ_URL" ]; then
		echo "Need GIT_PRIVATE_READ_URL"
		exit 1
	fi
	_update_status=0

	_repo
	_update_sources $REPOS
	_st=$?
	if [ $_update_status -eq 0 ]; then
		_update_status=$_st
	fi

	_repo_private
	_update_sources $REPOS_PRIVATE
	_st=$?
	if [ $_update_status -eq 0 ]; then
		_update_status=$_st
	fi

	# _update_sources $REPOS_RUNTIME
	# _st=$?
	# if [ $_update_status -eq 0 ]; then
	# 	_update_status=$_st
	# fi

	return $_update_status
}

_supervisor() {
	ln -sf /massbit/massbitroute/app/gbc /massbit/massbitroute/app/src/gbc
	ln -sf /massbit/massbitroute/app/gbc/bin/openresty /usr/local/openresty
	# apt-get update
	# apt-get install -y git apache2-utils supervisor jq python-is-python2 libssl-dev \
	# 	liburcu-dev libev-dev libsodium-dev libtool libunwind-dev libmaxminddb-dev

	if [ -f "/usr/bin/systemctl" ]; then

		systemctl enable supervisor
		systemctl start supervisor

	fi
	mkdir -p /etc/supervisor/conf.d
	cp supervisor.conf /etc/supervisor/conf.d/${TYPE}.conf
	if [ "$MBR_MODE" != "docker" ]; then
		supervisorctl update
	fi
}
_install_one() {
	_prepare
	_install_repos
}
_install() {
	_install_one
	_supervisor
}

_service_loki() {
	sed "s/_SITE_ROOT_/$SITE_ROOT1/g" $SITE_ROOT/etc/loki/config_tmpl.yaml >$SITE_ROOT/etc/loki/config.yaml
	$LOKI --config.file=$SITE_ROOT/etc/loki/config.yaml
}
_service_grafana() {
	sed "s/_SITE_ROOT_/$SITE_ROOT1/g" $SITE_ROOT/etc/grafana/config_tmpl.ini >$SITE_ROOT/etc/grafana/config.ini
	$GRAFANA -config $SITE_ROOT/etc/grafana/config.ini -homepath $GRAFANA_DIR
}

_reload() {
	pkill -f push.py
	#	curl -X POST http://127.0.0.1:44444/__internal_prometheus/-/reload

	for s in explorer_grafana explorer_loki monitor_client;do
		 $SITE_ROOT/cmd_server restart $s
	      done
		 

	$SITE_ROOT/cmd_server _update
	$SITE_ROOT/cmd_server update
	$SITE_ROOT/cmd_server start all
}

_save_env() {
	if [ \( -z "$EXPLORER_TYPE" \) -o \( -z "$EXPLORER_NETWORK" \) -o \( -z "$EXPLORER_BLOCKCHAIN" \) ]; then
		echo "EXPLORER_TYPE or EXPLORER_NETWORK or EXPLORER_BLOCKCHAIN missing"
		exit 1
	fi

	if [ -n "$EXPLORER_TYPE" ]; then echo $EXPLORER_TYPE >$SITE_ROOT/vars/EXPLORER_TYPE; fi
	if [ -n "$EXPLORER_NETWORK" ]; then echo $EXPLORER_NETWORK >$SITE_ROOT/vars/EXPLORER_NETWORK; fi
	if [ -n "$EXPLORER_BLOCKCHAIN" ]; then echo $EXPLORER_BLOCKCHAIN >$SITE_ROOT/vars/EXPLORER_BLOCKCHAIN; fi
}

_update_tag() {
	PORTAL_DOMAIN=portal.$DOMAIN
	git="git -C $SITE_ROOT"
	_v=$($git config --get remote.origin.url | awk -F'/' '{print $NF}')
	tmp=$(mktemp)
	curl -sfkL http://$PORTAL_DOMAIN/deploy/info/version/$_v >$tmp
	if [ $? -ne 0 ]; then
		rm $tmp
		return 0
	fi

	_tag=$(cat $tmp)

	rm $tmp

	_my_tag=$($git describe --tags)
	_tag_update=0
	if [ "$_tag" != "$_my_tag" ]; then
		$git fetch --all --tags --prune
		$git checkout $_tag
		_tag_update=1
	fi

	return $_tag_update

}

_update() {
	echo "Update"

	_save_env

	_st_update=0

	_update_repos
	_st=$?
	if [ $_st_update -eq 0 ]; then
		_st_update=$_st
	fi

	_update_tag
	_st=$?
	if [ $_st_update -eq 0 ]; then
		_st_update=$_st
	fi

	return $_st_update
}

_monitor() {
	_update
	is_reload=$?

	if [ $is_reload -ne 0 ]; then
		$0 _reload
	fi
}

_run() {
	rm -rf $SITE_ROOT/tmp/*
	_update
	$SITE_ROOT/start_server
}

$@
